openapi: 3.0.0
info:
  title: ATC WorkPlace API
  description: API for getting upgrade guidance.
  version: 1.0.0
servers:
  - url: https://atc-int.bmw-brilliance.cn/gateway
    description: ATC WorkPlace API Server
paths:
  /atc-workplace/v1/ossm/getUpgradeGuidance:
    get:
      summary: Get upgrade guidance for a specific component and version.
      description: Returns upgrade guidance for a given component and version.
      parameters:
        - name: component
          in: query
          required: true
          schema:
            type: string
            example: org.apache.activemq:activemq-ra
        - name: version
          in: query
          required: true
          schema:
            type: string
            example: 5.2.0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  upgradeGuidance:
                    type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: httpBearer
      bearerFormat: Bearer